# Generated by Django 4.2.1 on 2023-05-19 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='catagoryobj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.catagory'),
            preserve_default=False,
        ),
    ]
