# Generated by Django 4.2.1 on 2023-05-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_catagory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(db_column='Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='catagoryobj',
            field=models.ForeignKey(db_column='Catagory_ID', on_delete=django.db.models.deletion.CASCADE, to='tasks.catagory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_column='Name', default='palpala', max_length=100),
        ),
    ]
